spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangweiobs/config-repo.git
          username: wangweiobs@foxmail.com
          password: wwei1204
  application:
    name: config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#暴露/actuator/bus-refresh以至于自动更新
management:
  endpoints:
    web:
      exposure:
        include: "*"
